/* tslint:disable */
/* eslint-disable */
/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/application-api';
export * from './api/authentication-api';
export * from './api/bidding-api';
export * from './api/contracts-api';
export * from './api/loans-api';
export * from './api/opportunities-api';
export * from './api/portfolio-api';
export * from './api/reports-api';

