/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ApplicationApi,
  AuthenticationApi,
  BiddingApi,
  ContractsApi,
  LoansApi,
  OpportunitiesApi,
  PortfolioApi,
  ReportsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { Crowd4CashCustom } from "./client-custom";

export class Crowd4Cash extends Crowd4CashCustom {
  readonly application: ApplicationApi;
  readonly authentication: AuthenticationApi;
  readonly bidding: BiddingApi;
  readonly contracts: ContractsApi;
  readonly loans: LoansApi;
  readonly opportunities: OpportunitiesApi;
  readonly portfolio: PortfolioApi;
  readonly reports: ReportsApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.application = new ApplicationApi(configuration);
    this.authentication = new AuthenticationApi(configuration);
    this.bidding = new BiddingApi(configuration);
    this.contracts = new ContractsApi(configuration);
    this.loans = new LoansApi(configuration);
    this.opportunities = new OpportunitiesApi(configuration);
    this.portfolio = new PortfolioApi(configuration);
    this.reports = new ReportsApi(configuration);
  }

}
