/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AccountSummary
 */
export interface AccountSummary {
    /**
     * Balance at the beggining of the month
     * @type {number}
     * @memberof AccountSummary
     */
    'openingBalance'?: number;
    /**
     * Interest that investor receives for all investments during the months
     * @type {number}
     * @memberof AccountSummary
     */
    'interest'?: number;
    /**
     * Interest that investor receives for the late payments
     * @type {number}
     * @memberof AccountSummary
     */
    'defaultInterest'?: number;
    /**
     * Principal paid to investor during the month
     * @type {number}
     * @memberof AccountSummary
     */
    'principal'?: number;
    /**
     * Investor\'s investments during the month
     * @type {number}
     * @memberof AccountSummary
     */
    'investments'?: number;
    /**
     * Commission paid by investor during the month
     * @type {number}
     * @memberof AccountSummary
     */
    'commission'?: number;
    /**
     * Paid bids by investor during the months
     * @type {number}
     * @memberof AccountSummary
     */
    'deposits'?: number;
    /**
     * Deposits returned to investor during the month, due to cancelation of the agreement by the borrower
     * @type {number}
     * @memberof AccountSummary
     */
    'withdrawals'?: number;
    /**
     * Balance at the end of the month
     * @type {number}
     * @memberof AccountSummary
     */
    'closingBalance'?: number;
}

