/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AccountDetails
 */
export interface AccountDetails {
    /**
     * Receivables that are not paid to investor
     * @type {number}
     * @memberof AccountDetails
     */
    'availableCash'?: number;
    /**
     * Currency
     * @type {string}
     * @memberof AccountDetails
     */
    'availableCashCurrency'?: string | null;
    /**
     * Current principal balance + available cash
     * @type {number}
     * @memberof AccountDetails
     */
    'accountValue'?: number;
    /**
     * Current principal balance
     * @type {number}
     * @memberof AccountDetails
     */
    'investedAmount'?: number;
    /**
     * Current number of investments
     * @type {number}
     * @memberof AccountDetails
     */
    'numberOfInvestments'?: number;
    /**
     * The sum of \"bad debt\" and \"default\"
     * @type {number}
     * @memberof AccountDetails
     */
    'losses'?: number;
}

