/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Offers made by the other investors
 * @export
 * @interface ActiveBid
 */
export interface ActiveBid {
    /**
     * Investor pseudonym
     * @type {string}
     * @memberof ActiveBid
     */
    'pseudonym'?: string | null;
    /**
     * Bidding date
     * @type {string}
     * @memberof ActiveBid
     */
    'dateCreated'?: string | null;
    /**
     * Bid amount
     * @type {number}
     * @memberof ActiveBid
     */
    'amount'?: number;
}

