/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SchedulePayment } from './schedule-payment';

/**
 * Complete table of monthly payments to investor
 * @export
 * @interface AmortizationSchedule
 */
export interface AmortizationSchedule {
    /**
     * 
     * @type {Array<SchedulePayment>}
     * @memberof AmortizationSchedule
     */
    'payments'?: Array<SchedulePayment> | null;
}

