/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AutomaticBuilderOption
 */
export interface AutomaticBuilderOption {
    /**
     * Id of the automatic portfolio builder
     * @type {number}
     * @memberof AutomaticBuilderOption
     */
    'id'?: number;
    /**
     * Current investment using automatic autoinvest
     * @type {number}
     * @memberof AutomaticBuilderOption
     */
    'investmentCurrently'?: number;
    /**
     * Total amount that can be invested using automatic autoinvest
     * @type {number}
     * @memberof AutomaticBuilderOption
     */
    'totalAmountForInvestment'?: number;
    /**
     * Who\'s create/update the automatic portfolio builder?
     * @type {string}
     * @memberof AutomaticBuilderOption
     */
    'originators'?: string | null;
    /**
     * Minimum interest rate of the loan in which investor wants to invest
     * @type {number}
     * @memberof AutomaticBuilderOption
     */
    'interestRateFrom'?: number;
    /**
     * Mаџимум interest rate of the loan in which investor wants to invest
     * @type {number}
     * @memberof AutomaticBuilderOption
     */
    'interestRateTo'?: number;
    /**
     * Maximum bid amount per loan
     * @type {number}
     * @memberof AutomaticBuilderOption
     */
    'maximumPerBid'?: number;
    /**
     * Minimum bid amount per loan
     * @type {number}
     * @memberof AutomaticBuilderOption
     */
    'minimumPerBid'?: number;
    /**
     * Can investments be reinvested? - yes, no
     * @type {boolean}
     * @memberof AutomaticBuilderOption
     */
    'reinvest'?: boolean;
    /**
     * Investment level - conservative, balanced, growth
     * @type {string}
     * @memberof AutomaticBuilderOption
     */
    'investmentLevel'?: string | null;
    /**
     * Can investment be sold on the secondary market? - yes, no
     * @type {boolean}
     * @memberof AutomaticBuilderOption
     */
    'secondaryMarket'?: boolean;
    /**
     * Is automatic portfolio builder active? - yes, no
     * @type {boolean}
     * @memberof AutomaticBuilderOption
     */
    'isActive'?: boolean;
    /**
     * Date when automatic autoinvest starts to be used
     * @type {number}
     * @memberof AutomaticBuilderOption
     */
    'durationFrom'?: number;
    /**
     * Date when automatic autoinvest ends to be used
     * @type {number}
     * @memberof AutomaticBuilderOption
     */
    'durationTo'?: number;
    /**
     * Currency
     * @type {string}
     * @memberof AutomaticBuilderOption
     */
    'currency'?: string | null;
}

