/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Placing a bid on certain loan
 * @export
 * @interface Bid
 */
export interface Bid {
    /**
     * Loan ID which you want to invest in
     * @type {number}
     * @memberof Bid
     */
    'loanId': number;
    /**
     * Amount of the bid
     * @type {number}
     * @memberof Bid
     */
    'amount': number;
}

