/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A company that takes out a loan
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * Legal form of the company
     * @type {string}
     * @memberof Company
     */
    'legalForm'?: string | null;
    /**
     * Year established in the commercial resgister
     * @type {number}
     * @memberof Company
     */
    'yearEstablished'?: number | null;
    /**
     * Company headquarter
     * @type {string}
     * @memberof Company
     */
    'city'?: string | null;
    /**
     * Business sector
     * @type {string}
     * @memberof Company
     */
    'sector'?: string | null;
    /**
     * Number of employees
     * @type {number}
     * @memberof Company
     */
    'numberOfEmployees'?: number | null;
}

