/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectorInvestment } from './connector-investment';
import { ConnectorSummary } from './connector-summary';

/**
 * Report of investments of connected investors related to a connector
 * @export
 * @interface ConnectorReport
 */
export interface ConnectorReport {
    /**
     * 
     * @type {ConnectorSummary}
     * @memberof ConnectorReport
     */
    'connectorSummary'?: ConnectorSummary;
    /**
     * 
     * @type {Array<ConnectorInvestment>}
     * @memberof ConnectorReport
     */
    'connectorInvestments'?: Array<ConnectorInvestment> | null;
}

