/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectedInvestor } from './connected-investor';

/**
 * Connector account details
 * @export
 * @interface ConnectorSummary
 */
export interface ConnectorSummary {
    /**
     * Name of the connector
     * @type {string}
     * @memberof ConnectorSummary
     */
    'connectorName'?: string | null;
    /**
     * Number of pending investments
     * @type {number}
     * @memberof ConnectorSummary
     */
    'pendingInvestmentsCount'?: number;
    /**
     * Total amount of pending investments
     * @type {number}
     * @memberof ConnectorSummary
     */
    'pendingInvestmentsTotal'?: number;
    /**
     * Number of active investments
     * @type {number}
     * @memberof ConnectorSummary
     */
    'activeInvestmentsCount'?: number;
    /**
     * Total amount of active investments
     * @type {number}
     * @memberof ConnectorSummary
     */
    'activeInvestmentsTotal'?: number;
    /**
     * List of connected investors
     * @type {Array<ConnectedInvestor>}
     * @memberof ConnectorSummary
     */
    'connectedInvestors'?: Array<ConnectedInvestor> | null;
}

