/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An investment made by the connector on behalf of connected investor
 * @export
 * @interface ConnectorInvestment
 */
export interface ConnectorInvestment {
    /**
     * Id of the investor
     * @type {number}
     * @memberof ConnectorInvestment
     */
    'investorId'?: number;
    /**
     * Name of the investor
     * @type {string}
     * @memberof ConnectorInvestment
     */
    'investorName'?: string | null;
    /**
     * Amount of the bid
     * @type {number}
     * @memberof ConnectorInvestment
     */
    'bidAmount'?: number;
    /**
     * Date when the bid is placed
     * @type {string}
     * @memberof ConnectorInvestment
     */
    'bidDate'?: string | null;
    /**
     * Id of the loan
     * @type {number}
     * @memberof ConnectorInvestment
     */
    'loanId'?: number;
    /**
     * Amount of the loan
     * @type {number}
     * @memberof ConnectorInvestment
     */
    'loanAmount'?: number;
    /**
     * Duration of the loan in months
     * @type {number}
     * @memberof ConnectorInvestment
     */
    'loanDuration'?: number;
    /**
     * Interest rate of the loan
     * @type {number}
     * @memberof ConnectorInvestment
     */
    'loanInterest'?: number;
    /**
     * Rating of the loan - AA, A, B, C, D
     * @type {string}
     * @memberof ConnectorInvestment
     */
    'loanRating'?: string | null;
}

