/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An investor whose investments are made indirectly through connector
 * @export
 * @interface ConnectedInvestor
 */
export interface ConnectedInvestor {
    /**
     * Id of the investor
     * @type {number}
     * @memberof ConnectedInvestor
     */
    'investorId'?: number;
    /**
     * Type of the investor Private/Company
     * @type {string}
     * @memberof ConnectedInvestor
     */
    'investorType'?: string | null;
    /**
     * Name of the investor
     * @type {string}
     * @memberof ConnectedInvestor
     */
    'investorName'?: string | null;
    /**
     * Number of pending investments
     * @type {number}
     * @memberof ConnectedInvestor
     */
    'pendingInvestmentsCount'?: number;
    /**
     * Total amount of pending investments
     * @type {number}
     * @memberof ConnectedInvestor
     */
    'pendingInvestmentsTotal'?: number;
    /**
     * Number of active investments
     * @type {number}
     * @memberof ConnectedInvestor
     */
    'activeInvestmentsCount'?: number;
    /**
     * Total amount of active investments
     * @type {number}
     * @memberof ConnectedInvestor
     */
    'activeInvestmentsTotal'?: number;
}

