/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A bid that connector places on behalf of connected investors
 * @export
 * @interface ConnectorBid
 */
export interface ConnectorBid {
    /**
     * Investor ID
     * @type {number}
     * @memberof ConnectorBid
     */
    'investorId': number;
    /**
     * Loan ID on which you want to place a bid on behalf of your investors
     * @type {number}
     * @memberof ConnectorBid
     */
    'loanId': number;
    /**
     * Amount of the bid
     * @type {number}
     * @memberof ConnectorBid
     */
    'amount': number;
}

