/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Your loan agreement
 * @export
 * @interface Contract
 */
export interface Contract {
    /**
     * ID of the loan you have invested in
     * @type {number}
     * @memberof Contract
     */
    'loanId'?: number;
    /**
     * Name of the file (.PDF)
     * @type {string}
     * @memberof Contract
     */
    'contractName'?: string | null;
    /**
     * String representation of the contract that is encoded with base-64 digits
     * @type {string}
     * @memberof Contract
     */
    'contractFile'?: string | null;
}

