/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Borrower\'s credit report
 * @export
 * @interface Crif
 */
export interface Crif {
    /**
     * Credit score of the borrower in Crif
     * @type {number}
     * @memberof Crif
     */
    'creditScore'?: number;
    /**
     * Date when borrower score is checked
     * @type {string}
     * @memberof Crif
     */
    'checkingDate'?: string | null;
}

