/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Early repayment details
 * @export
 * @interface EarlyRepayment
 */
export interface EarlyRepayment {
    /**
     * date when the loan has been paid off
     * @type {string}
     * @memberof EarlyRepayment
     */
    'paymentDate'?: string | null;
    /**
     * the amount due and owed to satisfy the payoff of the loan
     * @type {number}
     * @memberof EarlyRepayment
     */
    'principalBalance'?: number;
    /**
     * Gross interest amount
     * @type {number}
     * @memberof EarlyRepayment
     */
    'interest'?: number;
    /**
     * investor commission amount
     * @type {number}
     * @memberof EarlyRepayment
     */
    'investorCommission'?: number;
    /**
     * a total amount that has been paid earlier to the investor
     * @type {number}
     * @memberof EarlyRepayment
     */
    'totalAmount'?: number;
}

