/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Monthly expenses of the borrower
 * @export
 * @interface Expenses
 */
export interface Expenses {
    /**
     * Tax to be paid
     * @type {number}
     * @memberof Expenses
     */
    'taxAtSource'?: number;
    /**
     * 
     * @type {string}
     * @memberof Expenses
     */
    'housingCondition'?: string | null;
    /**
     * Residential situation
     * @type {string}
     * @memberof Expenses
     */
    'residentalSituation'?: string | null;
    /**
     * Monthly rental cost
     * @type {number}
     * @memberof Expenses
     */
    'monthlyRent'?: number;
    /**
     * Are the rental costs shared?
     * @type {string}
     * @memberof Expenses
     */
    'payCostSolely'?: string | null;
    /**
     * Part of the rental costs (if shared)
     * @type {number}
     * @memberof Expenses
     */
    'monthlyCostPortion'?: number;
    /**
     * Monthly cost for homeowners
     * @type {number}
     * @memberof Expenses
     */
    'monthlyMortgage'?: number;
    /**
     * Amount of mortgage outstanding
     * @type {number}
     * @memberof Expenses
     */
    'mortgageAmount'?: number;
    /**
     * Are there any other open loans?
     * @type {string}
     * @memberof Expenses
     */
    'anotherLoan'?: string | null;
    /**
     * Name of lender of the outstanding loan
     * @type {string}
     * @memberof Expenses
     */
    'anotherLoanLender'?: string | null;
    /**
     * Amount of the outstanding loan
     * @type {number}
     * @memberof Expenses
     */
    'anotherLoanAmount'?: number;
    /**
     * Interest rate of the outstanding loan
     * @type {number}
     * @memberof Expenses
     */
    'anotherLoanInterestRate'?: number;
    /**
     * Monthly payment of the outstanding loan
     * @type {number}
     * @memberof Expenses
     */
    'anotherLoanMonthlyPayment'?: number;
    /**
     * Cost of insurances on a monthly basis
     * @type {number}
     * @memberof Expenses
     */
    'insuranceMonthlyCost'?: number;
    /**
     * Cost of private transportation on a monthly basis (cost of leasing etc.)
     * @type {number}
     * @memberof Expenses
     */
    'privateTransportMonthlyCost'?: number;
    /**
     * Cost of public transportation on a monthly basis
     * @type {number}
     * @memberof Expenses
     */
    'publicTransportMonthlyCost'?: number;
    /**
     * Are there any dependent children?
     * @type {string}
     * @memberof Expenses
     */
    'dependentChildren'?: string | null;
    /**
     * Number of children younger than ten years?
     * @type {number}
     * @memberof Expenses
     */
    'childrenYoungerThanTen'?: number;
    /**
     * Number of children older than ten years?
     * @type {number}
     * @memberof Expenses
     */
    'childrenOlderThanTen'?: number;
    /**
     * Are there any alimony or external child support
     * @type {string}
     * @memberof Expenses
     */
    'alimonyOrChildSupport'?: string | null;
    /**
     * Amount of alimony or external child support (if yes)
     * @type {number}
     * @memberof Expenses
     */
    'alimonyOrChildSupportAmount'?: number;
    /**
     * Are there any other recurring monthly cost?
     * @type {string}
     * @memberof Expenses
     */
    'furtherRecurringMonthlyCost'?: string | null;
    /**
     * Amount of any other recurruing monthly cost (if yes)
     * @type {number}
     * @memberof Expenses
     */
    'furtherRecurringMonthlyCost1Amount'?: number;
    /**
     * Description of any other recurruing monthly cost (if yes)
     * @type {string}
     * @memberof Expenses
     */
    'furtherRecurringMonthlyCost1Description'?: string | null;
    /**
     * Amount of any other recurruing monthly cost (if yes)
     * @type {number}
     * @memberof Expenses
     */
    'furtherRecurringMonthlyCost2Amount'?: number;
    /**
     * Description of any other recurruing monthly cost (if yes)
     * @type {string}
     * @memberof Expenses
     */
    'furtherRecurringMonthlyCost2Description'?: string | null;
}

