/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Company financial data in the last two years
 * @export
 * @interface Financial
 */
export interface Financial {
    /**
     * Liquid funds at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'liquidFunds_Year1'?: number;
    /**
     * Liquid funds at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'liquidFunds_Year2'?: number;
    /**
     * Accounts receivable at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'accountsReceivable_Year1'?: number;
    /**
     * Accounts receivable at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'accountsReceivable_Year2'?: number;
    /**
     * Stocks at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'stocks_Year1'?: number;
    /**
     * Stocks at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'stocks_Year2'?: number;
    /**
     * Other current assets at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'currentAssets_Other_Year1'?: number;
    /**
     * Other current assets at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'currentAssets_Other_Year2'?: number;
    /**
     * Total current assets at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'currentAssets_Year1_SUM'?: number;
    /**
     * Total current assets at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'currentAssets_Year2_SUM'?: number;
    /**
     * Machines and systems at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'machinesAndSystems_Year1'?: number;
    /**
     * Machines and systems at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'machinesAndSystems_Year2'?: number;
    /**
     * Facilities and vehicle at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'facilitiesAndVehiclePark_Year1'?: number;
    /**
     * Facilities and vehicle at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'facilitiesAndVehiclePark_Year2'?: number;
    /**
     * Other fixed assets at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'fixedAssets_Other_Year1'?: number;
    /**
     * Other fixed assets at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'fixedAssets_Other_Year2'?: number;
    /**
     * Total fixed assets at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'fixedAssets_Year1_SUM'?: number;
    /**
     * Total fixed assets at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'fixedAssets_Year2_SUM'?: number;
    /**
     * Accounts payable at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'accountsPayable_Year1'?: number;
    /**
     * Accounts payable at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'accountsPayable_Year2'?: number;
    /**
     * Total assets at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'totalAssets_Year1'?: number;
    /**
     * Total assets at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'totalAssets_Year2'?: number;
    /**
     * Short term loans at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'shortTermLoans_Year1'?: number;
    /**
     * Short term loans at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'shortTermLoans_Year2'?: number;
    /**
     * Other current liabilities at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'curentLiabilities_Other_Year1'?: number;
    /**
     * Other current liabilities at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'curentLiabilities_Other_Year2'?: number;
    /**
     * Total current liabilities at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'curentLiabilities_Year1_SUM'?: number;
    /**
     * Total current liabilities at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'curentLiabilities_Year2_SUM'?: number;
    /**
     * Long term loans at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'longTermLoans_Year1'?: number;
    /**
     * Long term loans at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'longTermLoans_Year2'?: number;
    /**
     * Accruals at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'accruals_Year1'?: number;
    /**
     * Accruals at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'accruals_Year2'?: number;
    /**
     * Other long term laiabilities at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'longTermLiabilities_Other_Year1'?: number;
    /**
     * Other long term laiabilities at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'longTermLiabilities_Other_Year2'?: number;
    /**
     * Total long term laiabilities at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'longTermLiabilities_Year1_SUM'?: number;
    /**
     * Total long term laiabilities at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'longTermLiabilities_Year2_SUM'?: number;
    /**
     * Equity at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'equity_Year1'?: number;
    /**
     * Equity at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'equity_Year2'?: number;
    /**
     * Total laiabilitie at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'totalLiabilities_Year1_SUM'?: number;
    /**
     * Total laiabilitie at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'totalLiabilities_Year2_SUM'?: number;
    /**
     * Sales Year 1
     * @type {number}
     * @memberof Financial
     */
    'salesProceeds_Year1'?: number;
    /**
     * Sales Year 2
     * @type {number}
     * @memberof Financial
     */
    'salesProceeds_Year2'?: number;
    /**
     * Cost of goods Year 1
     * @type {number}
     * @memberof Financial
     */
    'costOfGoods_Year1'?: number;
    /**
     * Cost of goods Year 2
     * @type {number}
     * @memberof Financial
     */
    'costOfGoods_Year2'?: number;
    /**
     * Gross profit Year 1
     * @type {number}
     * @memberof Financial
     */
    'grossProfit_Year1_SUM'?: number;
    /**
     * Gross profit Year 2
     * @type {number}
     * @memberof Financial
     */
    'grossProfit_Year2_SUM'?: number;
    /**
     * Operating expenses Year 1
     * @type {number}
     * @memberof Financial
     */
    'operatingExpenses_Year1'?: number;
    /**
     * Operating expenses Year 2
     * @type {number}
     * @memberof Financial
     */
    'operatingExpenses_Year2'?: number;
    /**
     * Ebidta Year 1
     * @type {number}
     * @memberof Financial
     */
    'ebidta_Year1_SUM'?: number;
    /**
     * Ebidta Year 2
     * @type {number}
     * @memberof Financial
     */
    'ebidta_Year2_SUM'?: number;
    /**
     * Depreciation Year 1
     * @type {number}
     * @memberof Financial
     */
    'depreciation_Year1'?: number;
    /**
     * Depreciation Year 2
     * @type {number}
     * @memberof Financial
     */
    'depreciation_Year2'?: number;
    /**
     * Ebit Year 1
     * @type {number}
     * @memberof Financial
     */
    'ebit_Year1_SUM'?: number;
    /**
     * Ebit Year 2
     * @type {number}
     * @memberof Financial
     */
    'ebit_Year2_SUM'?: number;
    /**
     * Financial expenses Year 1
     * @type {number}
     * @memberof Financial
     */
    'financialExpenses_Year1'?: number;
    /**
     * Financial expenses Year 2
     * @type {number}
     * @memberof Financial
     */
    'financialExpenses_Year2'?: number;
    /**
     * Net income before tax Year 1
     * @type {number}
     * @memberof Financial
     */
    'netIncomeBeforeTaxes_Year1_SUM'?: number;
    /**
     * Net income before tax Year 2
     * @type {number}
     * @memberof Financial
     */
    'netIncomeBeforeTaxes_Year2_SUM'?: number;
    /**
     * Income taxes Year 1
     * @type {number}
     * @memberof Financial
     */
    'incomeTaxes_Year1'?: number;
    /**
     * Income taxes Year 2
     * @type {number}
     * @memberof Financial
     */
    'incomeTaxes_Year2'?: number;
    /**
     * Net profit Year 1
     * @type {number}
     * @memberof Financial
     */
    'netProfit_Year1_SUM'?: number;
    /**
     * Net profit Year 2
     * @type {number}
     * @memberof Financial
     */
    'netProfit_Year2_SUM'?: number;
    /**
     * Financials at the beginning of Year 1
     * @type {number}
     * @memberof Financial
     */
    'beginningOfYearFinancials_Year1'?: number;
    /**
     * Financials at the beginning of Year 2
     * @type {number}
     * @memberof Financial
     */
    'beginningOfYearFinancials_Year2'?: number;
    /**
     * Cash flow of operating activities Year 1
     * @type {number}
     * @memberof Financial
     */
    'cashFlowOperating_Year1'?: number;
    /**
     * Cash flow of operating activities Year 2
     * @type {number}
     * @memberof Financial
     */
    'cashFlowOperating_Year2'?: number;
    /**
     * Cash flow of investing activities Year 1
     * @type {number}
     * @memberof Financial
     */
    'cashFlowInvesting_Year1'?: number;
    /**
     * Cash flow of investing activities Year 2
     * @type {number}
     * @memberof Financial
     */
    'cashFlowInvesting_Year2'?: number;
    /**
     * Cash flow of finansing activities Year 1
     * @type {number}
     * @memberof Financial
     */
    'cashFlowFinancing_Year1'?: number;
    /**
     * Cash flow of finansing activities Year 2
     * @type {number}
     * @memberof Financial
     */
    'cashFlowFinancing_Year2'?: number;
    /**
     * Total cash flow Year 1
     * @type {number}
     * @memberof Financial
     */
    'cashFlow_Year1_SUM'?: number;
    /**
     * Total cash flow Year 2
     * @type {number}
     * @memberof Financial
     */
    'cashFlow_Year2_SUM'?: number;
    /**
     * Financials at the end of Year 1
     * @type {number}
     * @memberof Financial
     */
    'endOfYearFinancials_Year1_SUM'?: number;
    /**
     * Financials at the end of Year 2
     * @type {number}
     * @memberof Financial
     */
    'endOfYearFinancials_Year2_SUM'?: number;
}

