/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Monthly income of the borrower
 * @export
 * @interface Income
 */
export interface Income {
    /**
     * Profession description
     * @type {string}
     * @memberof Income
     */
    'profession'?: string | null;
    /**
     * Type of employment
     * @type {string}
     * @memberof Income
     */
    'employmentType'?: string | null;
    /**
     * Is the employment under notice
     * @type {string}
     * @memberof Income
     */
    'employmentRelationshipUnderNotice'?: string | null;
    /**
     * Date since started with the current employer
     * @type {string}
     * @memberof Income
     */
    'workSince'?: string | null;
    /**
     * Number of salaries paid out to borrower
     * @type {number}
     * @memberof Income
     */
    'numberOfSalaries'?: number;
    /**
     * Monthly net income of the borrower
     * @type {number}
     * @memberof Income
     */
    'monthlyNetIncome'?: number;
    /**
     * Average bonus of the last 3 years
     * @type {number}
     * @memberof Income
     */
    'bonusAverage'?: number;
    /**
     * Additional income included?
     * @type {string}
     * @memberof Income
     */
    'additionalIncome'?: string | null;
    /**
     * Source of additional income
     * @type {string}
     * @memberof Income
     */
    'additionalIncomeType'?: string | null;
    /**
     * Amount of the additional income
     * @type {number}
     * @memberof Income
     */
    'additionalIncomeAmount'?: number;
    /**
     * Include partner income?
     * @type {string}
     * @memberof Income
     */
    'partnerIncome'?: string | null;
    /**
     * Profession description (Partner)
     * @type {string}
     * @memberof Income
     */
    'partnerProfession'?: string | null;
    /**
     * Date since started with the current employer (Partner)
     * @type {string}
     * @memberof Income
     */
    'partnerWorkSince'?: string | null;
    /**
     * Number of salaries paid out to partner
     * @type {number}
     * @memberof Income
     */
    'partnerNumberOfSalaries'?: number;
    /**
     * Monthly net income of the partner
     * @type {number}
     * @memberof Income
     */
    'partnerMonthlyNetIncome'?: number;
    /**
     * Average bonus of partner of the last three years
     * @type {number}
     * @memberof Income
     */
    'partnerBonusAverage'?: number;
}

