/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A loan application that is submitted by the intermediary company on behalf of their partner(s)
 * @export
 * @interface IntermediaryLoanApplication
 */
export interface IntermediaryLoanApplication {
    /**
     * ID of the partner that is buying an item. This ID can be taken from the Report endpoint and Intermediary route.
     * @type {number}
     * @memberof IntermediaryLoanApplication
     */
    'partnerId'?: number;
    /**
     * Description of the item you buy e.g. Car
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'purchaseItem'?: string | null;
    /**
     * Status of the item
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'itemStatus'?: string | null;
    /**
     * Name of the item
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'itemName'?: string | null;
    /**
     * Type of the item e.g. SUV, Van, Saloon, Cabriolet etc.
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'itemType'?: string | null;
    /**
     * Brand of the item
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'itemBrand'?: string | null;
    /**
     * Model of the item
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'itemModel'?: string | null;
    /**
     * Color of the item
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'itemColor'?: string | null;
    /**
     * Market value of the item you want to buy. Please notice that the Loan Amount will be 80% of this value.
     * @type {number}
     * @memberof IntermediaryLoanApplication
     */
    'itemMarketValue'?: number;
    /**
     * Date when the car was manufactured
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'manufactureDate'?: string | null;
    /**
     * Date when the item was registered very first time
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'firstRegistration'?: string | null;
    /**
     * Mileage of the item
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'mileage'?: string | null;
    /**
     * Certificate of the item
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'itemCertificate'?: string | null;
    /**
     * Serial number (aka VIN or Chassis No.)
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'serialNumber': string;
    /**
     * Identification number (aka Stammnummer)
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'identificationNumber': string;
    /**
     * Rental amount per month
     * @type {number}
     * @memberof IntermediaryLoanApplication
     */
    'rentalAmount'?: number;
    /**
     * The expected/approximate handover date (date when the car is expected to be handed over to the subscriber). Expected format: dd.MM.yyyy
     * @type {string}
     * @memberof IntermediaryLoanApplication
     */
    'handoverDate'?: string | null;
}

