/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A loan that was made on behalf of your partner
 * @export
 * @interface IntermediaryLoan
 */
export interface IntermediaryLoan {
    /**
     * Loan Id
     * @type {number}
     * @memberof IntermediaryLoan
     */
    'loanId'?: number;
    /**
     * Partner Id
     * @type {number}
     * @memberof IntermediaryLoan
     */
    'partnerId'?: number;
    /**
     * Name of the partner
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'partnerName'?: string | null;
    /**
     * Date of applicaton
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'dateCreated'?: string | null;
    /**
     * Date of approval
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'dateApproved'?: string | null;
    /**
     * Loan amount total
     * @type {number}
     * @memberof IntermediaryLoan
     */
    'loanAmount'?: number;
    /**
     * Interest rate of the loan
     * @type {number}
     * @memberof IntermediaryLoan
     */
    'interestRate'?: number;
    /**
     * Duration in months
     * @type {number}
     * @memberof IntermediaryLoan
     */
    'duration'?: number;
    /**
     * Rating of the loan - AA, A, B, C, D
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'loanRating'?: string | null;
    /**
     * Status of the loan
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'loanStatus'?: string | null;
    /**
     * Date of last payment received by the investor
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'lastPaymentDate'?: string | null;
    /**
     * Payment status - performing, late 1 to 15 days, Defaulted
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'performanceStatus'?: string | null;
    /**
     * Number od days late
     * @type {number}
     * @memberof IntermediaryLoan
     */
    'daysLate'?: number;
    /**
     * Is loan collaterialized? - Yes, No
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'collateral'?: string | null;
    /**
     * Collater Type - Real estate, Vehicle, Guarantor, Stock
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'collateralType'?: string | null;
    /**
     * Is loan insured? - Yes, No
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'insurance'?: string | null;
    /**
     * Unpaid Principal
     * @type {number}
     * @memberof IntermediaryLoan
     */
    'totalPrincipalRemaining'?: number;
    /**
     * Number of annuities that have been not paid yet.
     * @type {number}
     * @memberof IntermediaryLoan
     */
    'numberOfUnpaidAnnuities'?: number;
    /**
     * Currently paid principal
     * @type {number}
     * @memberof IntermediaryLoan
     */
    'totalRepaidPrincipal'?: number;
    /**
     * Currently paid interest
     * @type {number}
     * @memberof IntermediaryLoan
     */
    'totalRepaidInterest'?: number;
    /**
     * Date when the loan is paid to borrower
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'disbursementDate'?: string | null;
    /**
     * Date of the last instalment
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'maturityDate'?: string | null;
    /**
     * Description of the loan purpose
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'notes'?: string | null;
    /**
     * Web page where loan is desplayed in UI
     * @type {string}
     * @memberof IntermediaryLoan
     */
    'link'?: string | null;
}

