/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Handover Date Update
 * @export
 * @interface IntermediaryLoanHandoverDate
 */
export interface IntermediaryLoanHandoverDate {
    /**
     * Loan ID
     * @type {number}
     * @memberof IntermediaryLoanHandoverDate
     */
    'loanId'?: number;
    /**
     * The date when the car is handed over to the subscriber
     * @type {string}
     * @memberof IntermediaryLoanHandoverDate
     */
    'handoverDate'?: string | null;
}

