/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * rental location that is the borrower itself e.g. garage/shop/store
 * @export
 * @interface IntermediaryPartner
 */
export interface IntermediaryPartner {
    /**
     * Id of the partner
     * @type {number}
     * @memberof IntermediaryPartner
     */
    'partnerId'?: number;
    /**
     * Name of the partner
     * @type {string}
     * @memberof IntermediaryPartner
     */
    'partnerName'?: string | null;
    /**
     * legal form of the partner
     * @type {string}
     * @memberof IntermediaryPartner
     */
    'legalForm'?: string | null;
    /**
     * when the company was established
     * @type {string}
     * @memberof IntermediaryPartner
     */
    'yearEstablished'?: string | null;
    /**
     * Street address of the garage/shop/store
     * @type {string}
     * @memberof IntermediaryPartner
     */
    'address'?: string | null;
    /**
     * House number of the garage/shop/store
     * @type {string}
     * @memberof IntermediaryPartner
     */
    'houseNumber'?: string | null;
    /**
     * Zip code of the garage/shop/store
     * @type {string}
     * @memberof IntermediaryPartner
     */
    'zip'?: string | null;
    /**
     * City where the garage/shop/store resides
     * @type {string}
     * @memberof IntermediaryPartner
     */
    'city'?: string | null;
    /**
     * Phone number of the garage/shop/store
     * @type {string}
     * @memberof IntermediaryPartner
     */
    'phone'?: string | null;
    /**
     * IBAN of the company
     * @type {string}
     * @memberof IntermediaryPartner
     */
    'iban'?: string | null;
    /**
     * total number of loans
     * @type {number}
     * @memberof IntermediaryPartner
     */
    'numberOfLoans'?: number;
    /**
     * limit allowed by C4C e.g. 200\'000.00 CHF
     * @type {number}
     * @memberof IntermediaryPartner
     */
    'allowedLimitAmount'?: number;
    /**
     * An amount that is already used out e.g. 150\'000.00 CHF
     * @type {number}
     * @memberof IntermediaryPartner
     */
    'usedLimitAmount'?: number;
    /**
     * available amount e.g. 50\'000.00 CHF
     * @type {number}
     * @memberof IntermediaryPartner
     */
    'remainingLimitAmount'?: number;
}

