/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountDetails } from './account-details';
import { AccountSummary } from './account-summary';
import { AutoInvestSettings } from './auto-invest-settings';
import { Transacions } from './transacions';

/**
 * Investor account details and settings
 * @export
 * @interface InvestorAccount
 */
export interface InvestorAccount {
    /**
     * 
     * @type {AccountSummary}
     * @memberof InvestorAccount
     */
    'accountSummary'?: AccountSummary;
    /**
     * 
     * @type {Array<Transacions>}
     * @memberof InvestorAccount
     */
    'transactions'?: Array<Transacions> | null;
    /**
     * 
     * @type {AccountDetails}
     * @memberof InvestorAccount
     */
    'accountDetails'?: AccountDetails;
    /**
     * 
     * @type {AutoInvestSettings}
     * @memberof InvestorAccount
     */
    'autoInvestSettings'?: AutoInvestSettings;
}

