/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountStatement } from './account-statement';
import { ActiveBid } from './active-bid';
import { AmortizationSchedule } from './amortization-schedule';
import { Company } from './company';
import { Crif } from './crif';
import { Expenses } from './expenses';
import { Financial } from './financial';
import { Income } from './income';
import { Private } from './private';
import { Questionnaire } from './questionnaire';
import { TechnicalData } from './technical-data';

/**
 * Loan entity
 * @export
 * @interface Loan
 */
export interface Loan {
    /**
     * Loan Id
     * @type {number}
     * @memberof Loan
     */
    'id'?: number;
    /**
     * Date of applicaton
     * @type {string}
     * @memberof Loan
     */
    'dateCreated'?: string | null;
    /**
     * Date of approval
     * @type {string}
     * @memberof Loan
     */
    'dateApproved'?: string | null;
    /**
     * Loan amount total
     * @type {number}
     * @memberof Loan
     */
    'loanAmount'?: number;
    /**
     * Date of last payment received by the investor
     * @type {string}
     * @memberof Loan
     */
    'lastPaymentDate'?: string | null;
    /**
     * Interest rate of the loan
     * @type {number}
     * @memberof Loan
     */
    'interestRate'?: number;
    /**
     * Payment frequency defines how often payments will be made
     * @type {string}
     * @memberof Loan
     */
    'paymentFrequency'?: string | null;
    /**
     * Duration in months
     * @type {number}
     * @memberof Loan
     */
    'duration'?: number;
    /**
     * Type of the borrower - Private or SME
     * @type {string}
     * @memberof Loan
     */
    'borrowerType'?: string | null;
    /**
     * Type of the loan - Private or SME
     * @type {string}
     * @memberof Loan
     */
    'biddingType'?: string | null;
    /**
     * Loan type - POS loan, Private and SME
     * @type {string}
     * @memberof Loan
     */
    'loanType'?: string | null;
    /**
     * Purpose of the loan
     * @type {string}
     * @memberof Loan
     */
    'loanPurpose'?: string | null;
    /**
     * Rating of the loan - AA, A, B, C, D
     * @type {string}
     * @memberof Loan
     */
    'loanRating'?: string | null;
    /**
     * Status of the loan
     * @type {string}
     * @memberof Loan
     */
    'loanStatus'?: string | null;
    /**
     * Payment status - performing, late 1 to 15 days, Defaulted
     * @type {string}
     * @memberof Loan
     */
    'performanceStatus'?: string | null;
    /**
     * Number od days late
     * @type {number}
     * @memberof Loan
     */
    'daysLate'?: number;
    /**
     * Is loan collaterialized? - Yes, No
     * @type {string}
     * @memberof Loan
     */
    'collateral'?: string | null;
    /**
     * Collater Type - Real estate, Vehicle, Guarantor, Stock
     * @type {string}
     * @memberof Loan
     */
    'collateralType'?: string | null;
    /**
     * Is loan insured? - Yes, No
     * @type {string}
     * @memberof Loan
     */
    'insurance'?: string | null;
    /**
     * Unpaid Principal
     * @type {number}
     * @memberof Loan
     */
    'totalPrincipalRemaining'?: number;
    /**
     * Currently paid principal
     * @type {number}
     * @memberof Loan
     */
    'totalRepaidPrincipal'?: number;
    /**
     * Currently paid interest
     * @type {number}
     * @memberof Loan
     */
    'totalRepaidInterest'?: number;
    /**
     * End date of the project
     * @type {string}
     * @memberof Loan
     */
    'biddingEnd'?: string | null;
    /**
     * Date when the loan is paid to borrower
     * @type {string}
     * @memberof Loan
     */
    'disbursementDate'?: string;
    /**
     * Date of the last instalment
     * @type {string}
     * @memberof Loan
     */
    'maturityDate'?: string;
    /**
     * Description of the loan purpose
     * @type {string}
     * @memberof Loan
     */
    'notes'?: string | null;
    /**
     * Web page where loan is desplayed in UI
     * @type {string}
     * @memberof Loan
     */
    'link'?: string | null;
    /**
     * 
     * @type {Array<ActiveBid>}
     * @memberof Loan
     */
    'bids'?: Array<ActiveBid> | null;
    /**
     * 
     * @type {Private}
     * @memberof Loan
     */
    'borrowerPrivate'?: Private;
    /**
     * 
     * @type {Company}
     * @memberof Loan
     */
    'borrowerCompany'?: Company;
    /**
     * 
     * @type {Income}
     * @memberof Loan
     */
    'income'?: Income;
    /**
     * 
     * @type {Expenses}
     * @memberof Loan
     */
    'expenses'?: Expenses;
    /**
     * 
     * @type {Crif}
     * @memberof Loan
     */
    'crif'?: Crif;
    /**
     * 
     * @type {Questionnaire}
     * @memberof Loan
     */
    'questionnaire'?: Questionnaire;
    /**
     * 
     * @type {Financial}
     * @memberof Loan
     */
    'financial'?: Financial;
    /**
     * 
     * @type {AmortizationSchedule}
     * @memberof Loan
     */
    'amortizationSchedule'?: AmortizationSchedule;
    /**
     * 
     * @type {AccountStatement}
     * @memberof Loan
     */
    'accountStatement'?: AccountStatement;
    /**
     * 
     * @type {TechnicalData}
     * @memberof Loan
     */
    'technicalData'?: TechnicalData;
}

