/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Login
 */
export interface Login {
    /**
     * Your C4C username
     * @type {string}
     * @memberof Login
     */
    'username': string;
    /**
     * Your C4C password
     * @type {string}
     * @memberof Login
     */
    'password': string;
}

