/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ManualBuilderOption
 */
export interface ManualBuilderOption {
    /**
     * Id of the manual portfolio builder
     * @type {number}
     * @memberof ManualBuilderOption
     */
    'id'?: number;
    /**
     * Current investment using manual autoinvest
     * @type {number}
     * @memberof ManualBuilderOption
     */
    'investmentCurrently'?: number;
    /**
     * Who\'s create the manual portfolio builder?
     * @type {string}
     * @memberof ManualBuilderOption
     */
    'originators'?: string | null;
    /**
     * Is manual portfolio builder active? - yes, no
     * @type {boolean}
     * @memberof ManualBuilderOption
     */
    'isActive'?: boolean;
}

