/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ManualOptionRule
 */
export interface ManualOptionRule {
    /**
     * 
     * @type {string}
     * @memberof ManualOptionRule
     */
    'loanRating'?: string | null;
    /**
     * Total amount that can be invested using manual autoinvest
     * @type {number}
     * @memberof ManualOptionRule
     */
    'totalAmountForInvestment'?: number;
    /**
     * Minimum interest rate of the loan in which investor wants to invest
     * @type {number}
     * @memberof ManualOptionRule
     */
    'minimumInterestRate'?: number;
    /**
     * Minimum bid amount per loan
     * @type {number}
     * @memberof ManualOptionRule
     */
    'minimumPerBid'?: number;
    /**
     * Maximum bid amount per loan
     * @type {number}
     * @memberof ManualOptionRule
     */
    'maximumPerBid'?: number;
    /**
     * Can investments be reinvested? - yes, no
     * @type {boolean}
     * @memberof ManualOptionRule
     */
    'reinvest'?: boolean;
    /**
     * Can investment be sold on the secondary market? - yes, no
     * @type {boolean}
     * @memberof ManualOptionRule
     */
    'secondaryMarket'?: boolean;
    /**
     * Date when manual autoinvest starts to be used
     * @type {number}
     * @memberof ManualOptionRule
     */
    'durationFrom'?: number;
    /**
     * Date when manual autoinvest ends to be used
     * @type {number}
     * @memberof ManualOptionRule
     */
    'durationTo'?: number;
    /**
     * Is manual autoinvest enabled? yes. no
     * @type {boolean}
     * @memberof ManualOptionRule
     */
    'isEnabled'?: boolean;
    /**
     * Currency
     * @type {string}
     * @memberof ManualOptionRule
     */
    'currency'?: string | null;
}

