/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Error message in response to a client\'s request made to the API
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * Error type
     * @type {string}
     * @memberof ModelError
     */
    'type'?: string | null;
    /**
     * Error reason
     * @type {string}
     * @memberof ModelError
     */
    'message'?: string | null;
}

