/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ActiveBid } from './active-bid';
import { Company } from './company';
import { Expenses } from './expenses';
import { Financial } from './financial';
import { Income } from './income';
import { Private } from './private';
import { Questionnaire } from './questionnaire';
import { TechnicalData } from './technical-data';

/**
 * Investment opportunity
 * @export
 * @interface Opportunity
 */
export interface Opportunity {
    /**
     * Loan ID
     * @type {number}
     * @memberof Opportunity
     */
    'id'?: number;
    /**
     * Date when the loan application has been submitted.
     * @type {string}
     * @memberof Opportunity
     */
    'dateCreated'?: string | null;
    /**
     * Date when the loan application has been reviewed and approved.
     * @type {string}
     * @memberof Opportunity
     */
    'dateApproved'?: string | null;
    /**
     * An amount the borrower promises to repay
     * @type {number}
     * @memberof Opportunity
     */
    'loanAmount'?: number;
    /**
     * Interest rate in %
     * @type {number}
     * @memberof Opportunity
     */
    'interestRate'?: number;
    /**
     * Payment frequency defines how often payments will be made
     * @type {string}
     * @memberof Opportunity
     */
    'paymentFrequency'?: string | null;
    /**
     * Duration in months
     * @type {number}
     * @memberof Opportunity
     */
    'duration'?: number;
    /**
     * Borrower Type (Private or SME)
     * @type {string}
     * @memberof Opportunity
     */
    'borrowerType'?: string | null;
    /**
     * Loan type
     * @type {string}
     * @memberof Opportunity
     */
    'biddingType'?: string | null;
    /**
     * Loan type e.g. POS loan, Private or SME
     * @type {string}
     * @memberof Opportunity
     */
    'loanType'?: string | null;
    /**
     * Loan purpose category e.g. Education, Furnishing, Vehicle purchase, Wedding, Taxes, Refinancing etc.
     * @type {string}
     * @memberof Opportunity
     */
    'loanPurpose'?: string | null;
    /**
     * Crowd4Cash Rating
     * @type {string}
     * @memberof Opportunity
     */
    'loanRating'?: string | null;
    /**
     * Loan status e.g. In funding, Funded, Active, Closed, Defaulted etc.
     * @type {string}
     * @memberof Opportunity
     */
    'loanStatus'?: string | null;
    /**
     * Payment status e.g. Performing, Late 1 to 15 days, Late 16 to 30 days, Late more than 120 days, Defaulted, Cancelled, Finished prematurely, Paid off, etc.
     * @type {string}
     * @memberof Opportunity
     */
    'performanceStatus'?: string | null;
    /**
     * Is oan collaterialized?
     * @type {string}
     * @memberof Opportunity
     */
    'collateral'?: string | null;
    /**
     * Collater Type - Real estate, Vehicle, Guarantor, Stock
     * @type {string}
     * @memberof Opportunity
     */
    'collateralType'?: string | null;
    /**
     * Is loan insured?
     * @type {string}
     * @memberof Opportunity
     */
    'insurance'?: string | null;
    /**
     * An amount that is not funded yet
     * @type {number}
     * @memberof Opportunity
     */
    'openAmount'?: number;
    /**
     * End date of the project
     * @type {string}
     * @memberof Opportunity
     */
    'biddingEnd'?: string | null;
    /**
     * Description of the loan purpose
     * @type {string}
     * @memberof Opportunity
     */
    'notes'?: string | null;
    /**
     * Web page where loan is displayed in UI
     * @type {string}
     * @memberof Opportunity
     */
    'link'?: string | null;
    /**
     * 
     * @type {Private}
     * @memberof Opportunity
     */
    'borrowerPrivate'?: Private;
    /**
     * 
     * @type {Company}
     * @memberof Opportunity
     */
    'borrowerCompany'?: Company;
    /**
     * 
     * @type {Income}
     * @memberof Opportunity
     */
    'income'?: Income;
    /**
     * 
     * @type {Expenses}
     * @memberof Opportunity
     */
    'expenses'?: Expenses;
    /**
     * 
     * @type {Questionnaire}
     * @memberof Opportunity
     */
    'questionnaire'?: Questionnaire;
    /**
     * 
     * @type {Financial}
     * @memberof Opportunity
     */
    'financial'?: Financial;
    /**
     * 
     * @type {TechnicalData}
     * @memberof Opportunity
     */
    'technicalData'?: TechnicalData;
    /**
     * 
     * @type {Array<ActiveBid>}
     * @memberof Opportunity
     */
    'bids'?: Array<ActiveBid> | null;
}

