/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Investment } from './investment';
import { InvestorAccount } from './investor-account';

/**
 * 
 * @export
 * @interface Portfolio
 */
export interface Portfolio {
    /**
     * 
     * @type {InvestorAccount}
     * @memberof Portfolio
     */
    'investorAccount'?: InvestorAccount;
    /**
     * 
     * @type {Array<Investment>}
     * @memberof Portfolio
     */
    'investments'?: Array<Investment> | null;
}

