/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A person who takes out a loan
 * @export
 * @interface Private
 */
export interface Private {
    /**
     * Id of the borrower
     * @type {number}
     * @memberof Private
     */
    'borrowerId'?: number;
    /**
     * Zip of the borrower
     * @type {string}
     * @memberof Private
     */
    'zip'?: string | null;
    /**
     * City of the borrower
     * @type {string}
     * @memberof Private
     */
    'city'?: string | null;
    /**
     * Age of the borrower
     * @type {number}
     * @memberof Private
     */
    'age'?: number;
    /**
     * Gender of borrower
     * @type {string}
     * @memberof Private
     */
    'gender'?: string | null;
    /**
     * Borrower type
     * @type {string}
     * @memberof Private
     */
    'category'?: string | null;
    /**
     * Description of the housing conditon (used to calculate the living costs)
     * @type {string}
     * @memberof Private
     */
    'housingCondition'?: string | null;
    /**
     * Residential situation
     * @type {string}
     * @memberof Private
     */
    'residentialSituation'?: string | null;
    /**
     * Nationality
     * @type {string}
     * @memberof Private
     */
    'nationality'?: string | null;
    /**
     * Number of children
     * @type {number}
     * @memberof Private
     */
    'children'?: number;
    /**
     * Profession description
     * @type {string}
     * @memberof Private
     */
    'profession'?: string | null;
    /**
     * Date since started with the current employer
     * @type {string}
     * @memberof Private
     */
    'workSince'?: string | null;
    /**
     * Check in economical database successful
     * @type {string}
     * @memberof Private
     */
    'solvency'?: string | null;
    /**
     * Monthly net income of the borrower
     * @type {number}
     * @memberof Private
     */
    'monthlyNetIncome'?: number;
    /**
     * Income of the partner (if parter as a second borrower included)
     * @type {number}
     * @memberof Private
     */
    'partnerIncome'?: number;
    /**
     * Income minus expenses
     * @type {number}
     * @memberof Private
     */
    'availableAmount'?: number;
    /**
     * Relation of monthly payment with available amount (how much of the available amount is covered by the monthly payment)
     * @type {number}
     * @memberof Private
     */
    'availableAmountPercentage'?: number;
    /**
     * Monthly payment of the requested loan
     * @type {number}
     * @memberof Private
     */
    'monthlyPayment'?: number;
    /**
     * Are there any collection procedures in the last three years
     * @type {string}
     * @memberof Private
     */
    'collectionProcedures'?: string | null;
}

