/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RentalLoan } from './rental-loan';
import { Rentee } from './rentee';

/**
 * A rental company like Carify which rents user and new cars
 * @export
 * @interface RentalSummary
 */
export interface RentalSummary {
    /**
     * Name of the rental company
     * @type {string}
     * @memberof RentalSummary
     */
    'rentalName'?: string | null;
    /**
     * Number of rentees
     * @type {number}
     * @memberof RentalSummary
     */
    'numberOfRentees'?: number;
    /**
     * Number of loan applications
     * @type {number}
     * @memberof RentalSummary
     */
    'numberOfLoans'?: number;
    /**
     * A sum of all partner loans
     * @type {number}
     * @memberof RentalSummary
     */
    'loansTotalAmount'?: number;
    /**
     * List of your rentees
     * @type {Array<Rentee>}
     * @memberof RentalSummary
     */
    'rentees'?: Array<Rentee> | null;
    /**
     * List of your partner loan(s)
     * @type {Array<RentalLoan>}
     * @memberof RentalSummary
     */
    'loans'?: Array<RentalLoan> | null;
}

