/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RentalSummary } from './rental-summary';

/**
 * 
 * @export
 * @interface RentalReport
 */
export interface RentalReport {
    /**
     * 
     * @type {RentalSummary}
     * @memberof RentalReport
     */
    'rentalSummary'?: RentalSummary;
}

