/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * rental location that is the borrower itself e.g. garage/shop/store
 * @export
 * @interface Rentee
 */
export interface Rentee {
    /**
     * Id of the rentee
     * @type {number}
     * @memberof Rentee
     */
    'renteeId'?: number;
    /**
     * Rentee gender acronym. M stands for male and F for female.
     * @type {string}
     * @memberof Rentee
     */
    'gender'?: string | null;
    /**
     * First name of the rentee
     * @type {string}
     * @memberof Rentee
     */
    'firstName'?: string | null;
    /**
     * Last name of the rentee
     * @type {string}
     * @memberof Rentee
     */
    'lastName'?: string | null;
    /**
     * Birthdate of the rentee
     * @type {string}
     * @memberof Rentee
     */
    'birthdate'?: string | null;
    /**
     * E-mail address of the rentee
     * @type {string}
     * @memberof Rentee
     */
    'email'?: string | null;
    /**
     * Mobile phone number of the rentee
     * @type {string}
     * @memberof Rentee
     */
    'mobilePhone'?: string | null;
    /**
     * Street address of the garage/shop/store
     * @type {string}
     * @memberof Rentee
     */
    'streetAddress'?: string | null;
    /**
     * House number of the garage/shop/store
     * @type {string}
     * @memberof Rentee
     */
    'houseNumber'?: string | null;
    /**
     * Zip code of the rentee
     * @type {string}
     * @memberof Rentee
     */
    'zipCode'?: string | null;
    /**
     * City where the rentee resides
     * @type {string}
     * @memberof Rentee
     */
    'city'?: string | null;
    /**
     * IBAN of the rentee
     * @type {string}
     * @memberof Rentee
     */
    'iban'?: string | null;
}

