/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information regarding each monthly payment
 * @export
 * @interface SchedulePayment
 */
export interface SchedulePayment {
    /**
     * Number of the investor instalment
     * @type {number}
     * @memberof SchedulePayment
     */
    'annuityNumber'?: number;
    /**
     * Instalment due date
     * @type {string}
     * @memberof SchedulePayment
     */
    'annuityDate'?: string | null;
    /**
     * An amount the investor receives each month
     * @type {number}
     * @memberof SchedulePayment
     */
    'annuityAmount'?: number;
    /**
     * The principal part of the instalment
     * @type {number}
     * @memberof SchedulePayment
     */
    'principalPortion'?: number;
    /**
     * The interest part of the instalment
     * @type {number}
     * @memberof SchedulePayment
     */
    'interestPortion'?: number;
    /**
     * The insurance fee amount
     * @type {number}
     * @memberof SchedulePayment
     */
    'insuranceFee'?: number;
    /**
     * The administrative fee amount
     * @type {number}
     * @memberof SchedulePayment
     */
    'administrativeFee'?: number;
    /**
     * Monthly commission that investor pays
     * @type {number}
     * @memberof SchedulePayment
     */
    'commissionPortion'?: number;
    /**
     * Monthly net income of the investor (monthly interest - monthly commission)
     * @type {number}
     * @memberof SchedulePayment
     */
    'netIncome'?: number;
    /**
     * The amount of principal on the loan
     * @type {number}
     * @memberof SchedulePayment
     */
    'principalBalance'?: number;
    /**
     * The status of the instalment
     * @type {string}
     * @memberof SchedulePayment
     */
    'annuityStatus'?: string | null;
    /**
     * Is instalment is paid?
     * @type {string}
     * @memberof SchedulePayment
     */
    'isPaid'?: string | null;
    /**
     * A date when the instalment is paid.
     * @type {string}
     * @memberof SchedulePayment
     */
    'datePaid'?: string | null;
    /**
     * Some explanation of the instalment
     * @type {string}
     * @memberof SchedulePayment
     */
    'note'?: string | null;
}

