/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Technical data related to the client\'s use of the website
 * @export
 * @interface TechnicalData
 */
export interface TechnicalData {
    /**
     * Client Ip address
     * @type {string}
     * @memberof TechnicalData
     */
    'ipAddress'?: string | null;
    /**
     * Gets the raw user agent string of the client browser that has been provided.
     * @type {string}
     * @memberof TechnicalData
     */
    'userAgent'?: string | null;
    /**
     * URL of the client\'s previous request that linked to our website
     * @type {string}
     * @memberof TechnicalData
     */
    'urlReferrer'?: string | null;
    /**
     * Client browser
     * @type {string}
     * @memberof TechnicalData
     */
    'browserType'?: string | null;
    /**
     * Name of the browser
     * @type {string}
     * @memberof TechnicalData
     */
    'browserName'?: string | null;
    /**
     * Version of the browser
     * @type {string}
     * @memberof TechnicalData
     */
    'browserVersion'?: string | null;
    /**
     * Operating System
     * @type {string}
     * @memberof TechnicalData
     */
    'platform'?: string | null;
    /**
     * Does borrower use a beta version of the browser?
     * @type {string}
     * @memberof TechnicalData
     */
    'isBeta'?: string | null;
    /**
     * Does client connect by mobile device?
     * @type {string}
     * @memberof TechnicalData
     */
    'isMobileDevice'?: string | null;
    /**
     * Manufacturer of the mobile device
     * @type {string}
     * @memberof TechnicalData
     */
    'mobileDeviceManufacturer'?: string | null;
    /**
     * Model of the mobile device
     * @type {string}
     * @memberof TechnicalData
     */
    'mobileDeviceModel'?: string | null;
    /**
     * Is the \"Do Not Track\" setting in their web browser enabled?
     * @type {string}
     * @memberof TechnicalData
     */
    'isDoNotTrackEnabled'?: string | null;
    /**
     * Host of the client email
     * @type {string}
     * @memberof TechnicalData
     */
    'emailHost'?: string | null;
    /**
     * Is name of the client a part of the email?
     * @type {string}
     * @memberof TechnicalData
     */
    'isNameInEmail'?: string | null;
    /**
     * Is the name or the address lowercased?
     * @type {string}
     * @memberof TechnicalData
     */
    'isNameOrAddressLowercased'?: string | null;
    /**
     * How they found us?
     * @type {string}
     * @memberof TechnicalData
     */
    'channel'?: string | null;
}

