/*
C4C REST API

Access to the Crowd4Cash Crowdlending Platform through an API

The version of the OpenAPI document: 2.0.0
Contact: info@crowd4cash.ch

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * C4C Token
     * @type {string}
     * @memberof Token
     */
    'value'?: string | null;
    /**
     * By when you can use the token
     * @type {string}
     * @memberof Token
     */
    'expiryDate'?: string;
}

